### ISSUE TITLE
Tips after integration

### ISSUE THREAD

**Issue by dahun73** [Oshlack/speckle#4]
Hello, 

I'm trying to use this nice tool! I have 4 samples which were integrated using Seurat(Control : rep1 and rep2, Case : rep1 and rep2).So I have one integrated Seurat object now. In this case, How do I compare with Control vs. Case?
I could not find in tutorial except for short tips #13.

Thank you in advance!

**Comment by bphipson** [comment]
Have you performed clustering in order to identify cell types? There are three pieces of information that are required by speckle: sample (your 4 biological replicates), cell type/cluster (can be extracted from Idents(Seurat_obj0), group (Case vs Control). These three pieces of information should be in the metadata of your Seurat object and you can specify them directly in the propeller function. This will test for difference in cell type proportions between cases and controls for every cell type independently.

**Comment by dahun73** [comment]
@bphipson 

Thank you for tips! As you said, I annotated those metadata in Seurat object. It worked well. 

Thanks :)
